<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Website Content Configuration
    |--------------------------------------------------------------------------
    |
    | This file contain configuration for website content such as Page, Blog post,
    | and other type content. This file provides data abstraction for each
    | content types. Use "example" content type below as a reference for build
    | another content type.
    |
    */

    'example' => [
        'module_id' => 'content_example',
        'module_name' => 'example',
        'module_action' => [
            'index' => 'index',
            'create' => 'create',
            'store' => 'create',
            'edit' => 'edit',
            'update' => 'edit',
            'delete' => 'delete',
        ],
        'template' => 'example',
        'instruction' => 'Creating an example takes quite a few steps. Fill out the content below to present users relevant information of our website.',
        'field_container' => [
            0 => [
                'type' => 'custom',
                'label' => 'Data fields',
                'default_display' => 'show',
                'tab' => 'main',
                'field' => [
                    0 => [
                        'type' => 'heading',
                        'label' => 'text type',
                    ],
                    1 => [
                        'type' => 'text',
                        'id' => 'text_1',
                        'name' => 'text_1',
                        'label' => 'text 1',
                        'placeholder' => 'Text required',
                        'message_error' => [
                            'required' => 'Text 1 Required',
                        ],
                        'required' => 'yes',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    2 => [
                        'type' => 'text',
                        'id' => 'text_2',
                        'name' => 'text_2',
                        'label' => 'text 2',
                        'placeholder' => 'Text required & Min 5 chars',
                        'message_error' => [
                            'required' => 'Text 2 Required',
                            'minlength' => 'Min 5 characters',
                        ],
                        'required' => 'no',
                        'minlength' => '5',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    3 => [
                        'type' => 'text',
                        'id' => 'text_3',
                        'name' => 'text_3',
                        'label' => 'text 3',
                        'placeholder' => 'Text required & Max 7 chars',
                        'message_error' => [
                            'required' => 'Text 3 Required',
                            'maxlength' => 'Max 7 characters',
                        ],
                        'required' => 'no',
                        'maxlength' => '7',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    4 => [
                        'type' => 'text',
                        'id' => 'text_4',
                        'name' => 'text_4',
                        'label' => 'text 4',
                        'placeholder' => 'Min 5 characters & Max 7 chars',
                        'message_error' => [
                            'minlength' => 'Min 5 characters',
                            'maxlength' => 'Max 7 characters',
                        ],
                        'required' => 'no',
                        'minlength' => '5',
                        'maxlength' => '7',
                        'width' => '12',
                    ],
                    5 => [
                        'type' => 'digit',
                        'id' => 'digit',
                        'name' => 'digit',
                        'label' => 'digit only',
                        'placeholder' => 'Enter digits only',
                        'message_error' => [
                            'required' => 'This field is required',
                            'digits' => 'Please enter only digits',
                        ],
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    6 => [
                        'type' => 'number',
                        'id' => 'number',
                        'name' => 'number',
                        'label' => 'number only',
                        'placeholder' => 'Enter decimal number only',
                        'message_error' => [
                            'required' => 'This field is required',
                            'number' => 'Please enter a valid number',
                        ],
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    7 => [
                        'type' => 'username',
                        'id' => 'username',
                        'name' => 'username',
                        'label' => 'username',
                        'placeholder' => 'Use unique username',
                        'message_error' => [
                            'required' => 'Username required',
                            'minlength' => 'Username must be at least 4 characters',
                            'alphanumeric' => 'Letters, numbers, and underscores only are allowed'
                        ],
                        'required' => 'no',
                        'width' => '12',
                    ],
                    8 => [
                        'type' => 'password',
                        'id' => 'password',
                        'name' => 'password',
                        'label' => 'password',
                        'label_confirm' => 'repeat password',
                        'placeholder' => 'Password must be at least 6 characters and contain letter and numeric (A-Z,0-9)',
                        'placeholder_confirm' => 'Confirm your password',
                        'message_error' => [
                            'required' => 'Password required',
                            'required_confirm' => 'Please confirm your password',
                            'password' => 'Password must be at least 6 characters and contain letter and numeric (A-Z,0-9)',
                            'equalTo' => 'Password doesn\'t match',
                        ],
                        'required' => 'no',
                        'width' => '12',
                    ],
                    9 => [
                        'type' => 'passwordgenerator',
                        'id' => 'password_strong',
                        'name' => 'password_strong',
                        'label' => 'auto generated password',
                        'placeholder' => 'Enter your password',
                        'message_error' => [
                            'required' => 'Password required',
                            'password_strong' => 'Password must be at least 6 characters and contain letter, numeric, & symbol (A-Z,0-9,!#$&()*+<=>@[]^)',
                        ],
                        'required' => 'no',
                        'width' => '12',
                    ],
                    10 => [
                        'type' => 'email',
                        'id' => 'email',
                        'name' => 'email',
                        'label' => 'email',
                        'placeholder' => 'info@example.com',
                        'message_error' => [
                            'required' => 'Email Required',
                            'email' => 'Please enter a valid email address',
                        ],
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    11 => [
                        'type' => 'url',
                        'id' => 'url',
                        'name' => 'url',
                        'label' => 'URL',
                        'placeholder' => 'https://www.google.com',
                        'message_error' => [
                            'required' => 'URL address Required',
                            'url' => 'Please enter a valid email URL. Don\'t forget to use http:// or https://',
                        ],
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    12 => [
                        'type' => 'slug',
                        'id' => 'slug',
                        'name' => 'slug',
                        'label' => 'Slug',
                        'placeholder' => 'URL Slug',
                        'message_error' => [
                            'required' => 'Slug Required',
                            'slug' => 'Please use valid slug characters: a-z, 0-9, /, or -',
                        ],
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    13 => [
                        'type' => 'tag',
                        'id' => 'tag',
                        'name' => 'tag',
                        'label' => 'Tags',
                        'message_error' => '',
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    14 => [
                        'type' => 'textarea',
                        'id' => 'textarea',
                        'name' => 'textarea',
                        'label' => 'Simple textarea',
                        'placeholder' => 'Some content short description',
                        'message_error' => '',
                        'required' => 'no',
                        'width' => '12',
                        'row' => '3',
                        'same_as_default' => 'yes',
                    ],
                    14 => [
                        'type' => 'textareacounter',
                        'id' => 'maxlength',
                        'name' => 'maxlength',
                        'label' => 'Textarea with max length',
                        'placeholder' => 'This textarea has a limit of 170 characters',
                        'message_error' => '',
                        'required' => 'no',
                        'width' => '12',
                        'row' => '3',
                        'maxlength' => '170',
                        'same_as_default' => 'yes',
                    ],
                    15 => [
                        'type' => 'editor',
                        'id' => 'content',
                        'name' => 'content',
                        'label' => 'content',
                        'placeholder' => '',
                        'message_error' => '',
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    16 => [
                        'type' => 'heading',
                        'label' => 'Picker',
                    ],
                    17 => [
                        'type' => 'datepicker',
                        'id' => 'dob',
                        'name' => 'dob',
                        'label' => 'Date of Birth',
                        'message_error' => '',
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    18 => [
                        'type' => 'heading',
                        'label' => 'File',
                    ],
                    19 => [
                        'type' => 'file',
                        'id' => 'file_1',
                        'name' => 'file_1',
                        'label' => 'Specific file extensions',
                        'placeholder' => 'Allow only specific file extensions. In this example only <code>jpg</code>, <code>gif</code>, <code>png</code> and <code>txt</code> extensions are allowed.',
                        'message_error' => '',
                        'allowed_extension' => ['jpg','gif','png','txt'],
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    20 => [
                        'type' => 'file',
                        'id' => 'file_2',
                        'name' => 'file_2',
                        'label' => 'Specific file type',
                        'placeholder' => 'Allow only specific file type. In this example only <code>image</code>, <code>audio</code>, and <code>video</code> files are allowed.',
                        'message_error' => '',
                        'allowed_type' => ['audio','image','video'],
                        'required' => 'no',
                        'width' => '12',
                    ],
                    21 => [
                        'type' => 'file',
                        'id' => 'file_3',
                        'name' => 'file_3',
                        'label' => 'Specific file type and size',
                        'placeholder' => 'Allow only specific file type. In this example only <code>image</code>, <code>audio</code>, and <code>video</code> files are allowed and max <code>500KB</code>.',
                        'message_error' => '',
                        'allowed_type' => ['audio','image','video'],
                        'maxfilesize' => '500', // in KB
                        'required' => 'no',
                        'width' => '12',
                    ],
                    22 => [
                        'type' => 'avatar',
                        'id' => 'avatar',
                        'name' => 'avatar',
                        'label' => 'Profile picture',
                        'placeholder' => 'Select your profile picture. Max file size <code>2MB</code>.',
                        'message_error' => [
                            'filesize' => 'File exceeds maximum allowed upload size. Please retry your upload!',
                        ],
                        'maxfilesize' => '2000', // in KB
                        'shape' => 'rounded', // square or rounded
                        'required' => 'no',
                        'width' => '12',
                    ],
                    23 => [
                        'type' => 'heading',
                        'label' => 'Grid',
                    ],
                    24 => [
                        'type' => 'text',
                        'id' => 'title',
                        'name' => 'title',
                        'label' => 'Page Title',
                        'placeholder' => 'Enter page title here',
                        'message_error' => [
                            'required' => 'Title Required',
                        ],
                        'required' => 'no',
                        'width' => '12',
                    ],
                    25 => [
                        'type' => 'text',
                        'id' => 'address_1',
                        'name' => 'address_1',
                        'label' => 'Address Line 1',
                        'placeholder' => 'Street Name',
                        'message_error' => [
                            'required' => 'Address Required',
                        ],
                        'required' => 'no',
                        'width' => '6',
                        'same_as_default' => 'yes',
                    ],
                    26 => [
                        'type' => 'text',
                        'id' => 'address_2',
                        'name' => 'address_2',
                        'label' => 'Address Line 2',
                        'placeholder' => 'Street Block',
                        'message_error' => [
                            'required' => 'Address Required',
                        ],
                        'required' => 'no',
                        'width' => '6',
                        'same_as_default' => 'yes',
                    ],
                    27 => [
                        'type' => 'text',
                        'id' => 'first_name',
                        'name' => 'first_name',
                        'label' => 'First Name',
                        'placeholder' => 'First Name',
                        'message_error' => [
                            'required' => 'First Name Required',
                        ],
                        'required' => 'no',
                        'width' => '4',
                    ],
                    28 => [
                        'type' => 'text',
                        'id' => 'middle_name',
                        'name' => 'middle_name',
                        'label' => 'Middle Name',
                        'placeholder' => 'Middle Name',
                        'message_error' => [
                            'required' => 'Middle Name Required',
                        ],
                        'required' => 'no',
                        'width' => '4',
                    ],
                    29 => [
                        'type' => 'text',
                        'id' => 'last_name',
                        'name' => 'last_name',
                        'label' => 'Last Name',
                        'placeholder' => 'Last Name',
                        'message_error' => [
                            'required' => 'Last Name Required',
                        ],
                        'required' => 'no',
                        'width' => '4',
                    ],
                    30 => [
                        'type' => 'heading',
                        'label' => 'Data Masked',
                    ],
                    31 => [
                        'type' => 'phone',
                        'id' => 'phone',
                        'name' => 'phone',
                        'label' => 'Phone',
                        'placeholder' => 'Enter your phone',
                        'message_error' => [
                            'required' => 'Phone Number Required',
                            'phone' => 'Please input valid phone number',
                        ],
                        'required' => 'no',
                        'width' => '6',
                        'same_as_default' => 'yes',
                    ],
                    32 => [
                        'type' => 'creditcard',
                        'id' => 'cc',
                        'name' => 'cc',
                        'label' => 'Credit card',
                        'placeholder' => 'Enter your credit card number',
                        'message_error' => [
                            'required' => 'Credit Card Number Required',
                            'cc' => 'Please input valid credit card number',
                        ],
                        'required' => 'no',
                        'width' => '6',
                        'same_as_default' => 'yes',
                    ],
                    33 => [
                        'type' => 'heading',
                        'label' => 'Checkboxes & Radios',
                    ],
                    34 => [
                        'type' => 'radio',
                        'id' => 'gender',
                        'name' => 'gender',
                        'label' => 'Gender',
                        'message_error' => [
                            'required' => 'Gender Required',
                        ],
                        'data' => [
                            '0' => '<i class="icon-man"></i> Male',
                            '1' => '<i class="icon-woman"></i> Female',
                        ],
                        'style' => 'inline',
                        'required' => 'no',
                        'width' => '6',
                    ],
                    35 => [
                        'type' => 'radio',
                        'id' => 'gender2',
                        'name' => 'gender2',
                        'label' => 'Gender',
                        'message_error' => [
                            'required' => 'Gender Required',
                        ],
                        'data' => [
                            '0' => '<i class="icon-man"></i> Male',
                            '1' => '<i class="icon-woman"></i> Female',
                        ],
                        'required' => 'no',
                        'width' => '6',
                    ],
                    36 => [
                        'type' => 'checkbox',
                        'id' => 'hobby1',
                        'name' => 'hobby1',
                        'label' => 'Hobbies',
                        'message_error' => [
                            'required' => 'Hobby Required',
                        ],
                        'data' => [
                            0 =>[
                                'value' => 'travelling',
                                'label' => '<i class="icon-airplane2"></i> Travelling',
                                'checked' => '',
                            ],
                            1 =>[
                                'value' => 'basketball',
                                'label' => '<i class="icon-dribbble"></i> Basketball',
                                'checked' => '',
                            ],
                            2 =>[
                                'value' => 'cycling',
                                'label' => '<i class="icon-bike"></i> Cycling',
                                'checked' => 'checked',
                            ],
                        ],
                        'required' => 'no',
                        'width' => '12',
                    ],
                    37 => [
                        'type' => 'checkbox',
                        'id' => 'hobby2',
                        'name' => 'hobby2',
                        'label' => 'Hobbies',
                        'message_error' => [
                            'required' => 'Hobby Required',
                        ],
                        'data' => [
                            0 =>[
                                'value' => 'travelling',
                                'label' => '<i class="icon-airplane2"></i> Travelling',
                                'checked' => '',
                            ],
                            1 =>[
                                'value' => 'basketball',
                                'label' => '<i class="icon-dribbble"></i> Basketball',
                                'checked' => 'checked',
                            ],
                            2 =>[
                                'name' => 'hobby_6',
                                'value' => 'cycling',
                                'label' => '<i class="icon-bike"></i> Cycling',
                                'checked' => '',
                            ],
                        ],
                        'style' => 'inline',
                        'required' => 'no',
                        'width' => '12',
                    ],
                    38 => [
                        'type' => 'toggle',
                        'id' => 'facility',
                        'name' => 'facility',
                        'label' => 'Villa Facilities',
                        'message_error' => [
                            'required' => 'Villa Facilities Required',
                        ],
                        'data' => [
                            0 =>[
                                'value' => 'internet',
                                'label' => '<i class="icon-earth"></i> Internet',
                                'checked' => 'checked',
                            ],
                            1 =>[
                                'value' => 'garage',
                                'label' => '<i class="icon-car"></i> Garage',
                                'checked' => 'checked',
                            ],
                            3 =>[
                                'value' => 'airconditioner',
                                'label' => '<i class="icon-snowflake"></i> Air Conditioner',
                                'checked' => 'checked',
                            ],
                            4 =>[
                                'value' => 'security',
                                'label' => '<i class="icon-shield-check"></i> Security',
                                'checked' => '',
                            ],
                        ],
                        'color_schema' => '', // '', switchery-primary, switchery-danger, switchery-warning, switchery-info
                        'required' => 'no',
                        'width' => '12',
                    ],
                    39 => [
                        'type' => 'toggle',
                        'id' => 'facility1',
                        'name' => 'facilities',
                        'label' => 'Villa Facilities (in splited grid)',
                        'message_error' => [
                            'required' => 'Villa Facilities Required',
                        ],
                        'data' => [
                            0 =>[
                                'value' => 'internet',
                                'label' => '<i class="icon-earth"></i> Internet',
                                'checked' => 'checked',
                            ],
                            1 =>[
                                'value' => 'garage',
                                'label' => '<i class="icon-car"></i> Garage',
                                'checked' => '',
                            ],
                        ],
                        'color_schema' => '', // '', switchery-primary, switchery-danger, switchery-warning, switchery-info
                        'required' => 'no',
                        'width' => '6',
                    ],
                    40 => [
                        'type' => 'toggle',
                        'id' => 'facility2',
                        'name' => 'facilities',
                        'label' => '&nbsp;',
                        'message_error' => [
                            'required' => 'Villa Facilities Required',
                        ],
                        'data' => [
                            0 =>[
                                'value' => 'airconditioner',
                                'label' => '<i class="icon-snowflake"></i> Air Conditioner',
                                'checked' => 'checked',
                            ],
                            1 =>[
                                'value' => 'security',
                                'label' => '<i class="icon-shield-check"></i> Security',
                                'checked' => 'checked',
                            ],
                        ],
                        'color_schema' => '', // '', switchery-primary, switchery-danger, switchery-warning, switchery-info
                        'required' => 'no',
                        'width' => '6',
                    ],
                    41 => [
                        'type' => 'switch',
                        'id' => 'like',
                        'name' => 'like',
                        'label' => 'Do you agree with me ?',
                        'message_error' => [
                            'required' => 'Please choose one',
                        ],
                        'data' => [
                            'on' =>[
                                'value' => 'yes',
                                'label' => 'Yes',
                                'color' => 'primary', // 'default', 'primary', 'danger', 'warning', 'info'
                            ],
                            'off' =>[
                                'value' => 'no',
                                'label' => 'No',
                                'color' => 'danger', // 'default', 'primary', 'danger', 'warning', 'info'
                            ],
                        ],
                        'checked' => '',
                        'required' => 'no',
                        'width' => '12',
                    ],
                    42 => [
                        'type' => 'switch',
                        'id' => 'like_pizza',
                        'name' => 'like_pizza',
                        'label' => 'Do you like Pizza ?',
                        'message_error' => [
                            'required' => 'Please choose one',
                        ],
                        'data' => [
                            'on' =>[
                                'value' => 'like',
                                'label' => '<i class="icon-thumbs-up2"></i>',
                                'color' => 'primary', // 'default', 'primary', 'danger', 'warning', 'info'
                            ],
                            'off' =>[
                                'value' => 'dislike',
                                'label' => '<i class="icon-thumbs-down2"></i>',
                                'color' => 'default', // 'default', 'primary', 'danger', 'warning', 'info'
                            ],
                        ],
                        'checked' => 'checked',
                        'required' => 'no',
                        'width' => '12',
                    ],
                    43 => [
                        'type' => 'heading',
                        'label' => 'Select',
                    ],
                    44 => [
                        'type' => 'select',
                        'id' => 'select_basic',
                        'name' => 'select_basic',
                        'label' => 'Basic Select - static data',
                        'placeholder' => 'Choose ...',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'data' => [
                            0 => [
                                'value' => 'AK',
                                'text' => 'Alaska',
                                'icon' => '',
                            ],
                            1 => [
                                'value' => 'HI',
                                'text' => 'Hawaii',
                                'icon' => '',
                            ],
                            2 => [
                                'value' => 'CA',
                                'text' => 'California',
                                'icon' => '',
                            ],
                            3 => [
                                'value' => 'NV',
                                'text' => 'Nevada',
                                'icon' => '',
                            ],
                            4 => [
                                'value' => 'OR',
                                'text' => 'Oregon',
                                'icon' => '',
                            ],
                        ],
                        'required' => 'no',
                        'width' => '6',
                        'same_as_default' => 'yes',
                    ],
                    45 => [
                        'type' => 'select',
                        'id' => 'select_multi',
                        'name' => 'select_multi',
                        'label' => 'Multi Select - static data',
                        'placeholder' => 'Options display alternative in multiple select',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'data' => [
                            0 => [
                                'value' => 'AK',
                                'text' => 'Alaska',
                                'icon' => '',
                            ],
                            1 => [
                                'value' => 'HI',
                                'text' => 'Hawaii',
                                'icon' => '',
                            ],
                            2 => [
                                'value' => 'CA',
                                'text' => 'California',
                                'icon' => '',
                            ],
                            3 => [
                                'value' => 'NV',
                                'text' => 'Nevada',
                                'icon' => '',
                            ],
                            4 => [
                                'value' => 'OR',
                                'text' => 'Oregon',
                                'icon' => '',
                            ],
                        ],
                        'multiselect' => 'yes',
                        'required' => 'no',
                        'width' => '6',
                        'same_as_default' => 'yes',
                    ],
                    46 => [
                        'type' => 'select',
                        'id' => 'select_opt',
                        'name' => 'select_opt',
                        'label' => 'Multi Select Option Group - static data',
                        'placeholder' => 'Options display alternative in multiple select group',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'data' => [
                            0 => [
                                'grouplabel' => 'File types',
                                'option' => [
                                    0 => [
                                        'value' => 'pdf',
                                        'text' => 'PDF',
                                        'icon' => '',
                                    ],
                                    1 => [
                                        'value' => 'word',
                                        'text' => 'Word',
                                        'icon' => '',
                                    ],
                                    2 => [
                                        'value' => 'excel',
                                        'text' => 'Excel',
                                        'icon' => '',
                                    ],
                                    3 => [
                                        'value' => 'openoffice',
                                        'text' => 'Open Office',
                                        'icon' => '',
                                    ],
                                ],
                            ],
                            1 => [
                                'grouplabel' => 'Browser',
                                'option' => [
                                    0 => [
                                        'value' => 'chrome',
                                        'text' => 'Chrome',
                                        'icon' => '',
                                    ],
                                    1 => [
                                        'value' => 'firefox',
                                        'text' => 'Firefox',
                                        'icon' => '',
                                    ],
                                    2 => [
                                        'value' => 'safari',
                                        'text' => 'Safari',
                                        'icon' => '',
                                    ],
                                    3 => [
                                        'value' => 'opera',
                                        'text' => 'Opera',
                                        'icon' => '',
                                    ],
                                    4 => [
                                        'value' => 'IE',
                                        'text' => 'Internet Explorer',
                                        'icon' => '',
                                    ],
                                ],
                            ],
                        ],
                        'multiselect' => 'yes',
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    47 => [
                        'type' => 'select',
                        'id' => 'select_icon',
                        'name' => 'select_icon',
                        'label' => 'Select Option Group with Icon - static data',
                        'placeholder' => 'Choose ...',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'data' => [
                            0 => [
                                'grouplabel' => 'File types',
                                'option' => [
                                    0 => [
                                        'value' => 'pdf',
                                        'text' => 'PDF',
                                        'icon' => 'icon-file-pdf',
                                    ],
                                    1 => [
                                        'value' => 'word',
                                        'text' => 'Word',
                                        'icon' => 'icon-file-word',
                                    ],
                                    2 => [
                                        'value' => 'excel',
                                        'text' => 'Excel',
                                        'icon' => 'icon-file-excel',
                                    ],
                                    3 => [
                                        'value' => 'openoffice',
                                        'text' => 'Open Office',
                                        'icon' => 'icon-file-openoffice',
                                    ],
                                ],
                            ],
                            1 => [
                                'grouplabel' => 'Browser',
                                'option' => [
                                    0 => [
                                        'value' => 'chrome',
                                        'text' => 'Chrome',
                                        'icon' => 'icon-chrome',
                                    ],
                                    1 => [
                                        'value' => 'firefox',
                                        'text' => 'Firefox',
                                        'icon' => 'icon-firefox',
                                    ],
                                    2 => [
                                        'value' => 'safari',
                                        'text' => 'Safari',
                                        'icon' => 'icon-safari',
                                    ],
                                    3 => [
                                        'value' => 'opera',
                                        'text' => 'Opera',
                                        'icon' => 'icon-opera',
                                    ],
                                    4 => [
                                        'value' => 'IE',
                                        'text' => 'Internet Explorer',
                                        'icon' => 'icon-IE',
                                    ],
                                ],
                            ],
                        ],
                        'required' => 'no',
                        'width' => '12',
                    ],
                    48 => [
                        'type' => 'select',
                        'id' => 'select_basic_2',
                        'name' => 'select_basic_2',
                        'label' => 'Basic Select - dynamic data',
                        'placeholder' => 'Choose ...',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'datasource' => '#select_basic_2_datasource',
                        'required' => 'no',
                        'width' => '6',
                    ],
                    49 => [
                        'type' => 'select',
                        'id' => 'select_multi_2',
                        'name' => 'select_multi_2',
                        'label' => 'Multi Select - dynamic data',
                        'placeholder' => 'Options display alternative in multiple select',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'multiselect' => 'yes',
                        'datasource' => '#select_basic_2_datasource',
                        'required' => 'no',
                        'width' => '6',
                    ],
                    50 => [
                        'type' => 'select',
                        'id' => 'select_opt_2',
                        'name' => 'select_opt_2',
                        'label' => 'Multi Select Option Group - dynamic data',
                        'placeholder' => 'Options display alternative in multiple select group',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'datasource' => '#select_basic_2_datasource_group',
                        'multiselect' => 'yes',
                        'required' => 'no',
                        'width' => '12',
                    ],
                    51 => [
                        'type' => 'select',
                        'id' => 'select_opt_2_icon',
                        'name' => 'select_opt_2_icon',
                        'label' => 'Select Option Group with Icon - dynamic data',
                        'placeholder' => 'Choose ...',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'datasource' => '#select_basic_2_datasource_group_icon',
                        'required' => 'no',
                        'width' => '12',
                    ],
                    52 => [
                        'type' => 'select',
                        'id' => 'select_auto_width',
                        'name' => 'select_auto_width',
                        'label' => 'Auto width',
                        'placeholder' => 'Choose ...',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'datasource' => '#select_basic_2_datasource_group',
                        'required' => 'no',
                        'selectwidth' => 'auto',
                        'width' => '6',
                    ],
                    53 => [
                        'type' => 'select',
                        'id' => 'select_search',
                        'name' => 'select_search',
                        'label' => 'Search Capability',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'datasource' => '#select_basic_2_datasource_group',
                        'required' => 'no',
                        'search' => 'yes',
                        'multiselect' => 'yes',
                        'width' => '12',
                    ],
                    54 => [
                        'type' => 'select',
                        'id' => 'select_all',
                        'name' => 'select_all',
                        'label' => 'Select All / deselect all methods',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'datasource' => '#select_basic_2_datasource_group',
                        'required' => '',
                        'multiselect' => 'yes',
                        'button_select_all' => 'yes',
                        'button_deselect_all' => 'yes',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                ],
            ],
            1 => [
                'type' => 'media',
                'label' => 'media',
                'default_display' => 'show',
                'tab' => 'main',
                'feature' => ['image','gallery','video'],
            ],
            2 => [
                'type' => 'seo',
                'label' => 'search engine optimization',
                'default_display' => 'hide',
                'tab' => 'main',
                'feature' => ['keywords','advanced'],
            ],
        ],
    ],
    'page' => [
        'module_id' => 'content_page',
        'module_name' => 'page',
        'module_action' => [
            'index' => 'index',
            'create' => 'create',
            'store' => 'create',
            'edit' => 'edit',
            'update' => 'edit',
            'delete' => 'delete',
        ],
        'template' => 'default',
        'instruction' => 'Creating a page takes quite a few steps. Fill out the page\'s content below to present users relevant information of our website.',
        'field_container' => [
            0 => [
                'type' => 'custom',
                'label' => 'general',
                'default_display' => 'show',
                'field' => [
                    0 => [
                        'type' => 'text',
                        'id' => 'title',
                        'name' => 'title',
                        'label' => 'page title',
                        'placeholder' => 'Enter page title here',
                        'message_error' => [
                            'required' => 'Title Required',
                        ],
                        'required' => 'yes',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    1 => [
                        'type' => 'textareacounter',
                        'id' => 'short_description',
                        'name' => 'short_description',
                        'label' => 'Short Description',
                        'placeholder' => 'This short description has a limit of 170 characters',
                        'message_error' => '',
                        'required' => 'no',
                        'width' => '12',
                        'row' => '5',
                        'maxlength' => '170',
                        'same_as_default' => 'yes',
                    ],
                    2 => [
                        'type' => 'editor',
                        'id' => 'content',
                        'name' => 'content',
                        'label' => 'content',
                        'placeholder' => '',
                        'message_error' => '',
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                ],
            ],
            1 => [
                'type' => 'media',
                'label' => 'media',
                'default_display' => 'show',
                'use_panel' => 'yes',
                'feature' => ['image','gallery'],
            ],
            2 => [
                'type' => 'seo',
                'label' => 'search engine optimization',
                'default_display' => 'hide',
                'feature' => ['keywords','advanced'],
            ],
        ],
    ],
    'content_post' => [
        'module_id' => 'content_post',
        'module_name' => 'post',
        'module_action' => [
            'index' => 'index',
            'create' => 'create',
            'store' => 'create',
            'edit' => 'edit',
            'update' => 'edit',
            'delete' => 'delete',
        ],
    ],
    'category_post' => [
        'module_id' => 'category_post',
        'module_name' => 'category post',
        'module_action' => [
            'category_index' => 'index',
            'category_create' => 'create',
            'category_store' => 'create',
            'category_edit' => 'edit',
            'category_update' => 'edit',
            'category_delete' => 'delete',
        ],
        'template' => 'categorypost',
        'instruction' => 'Creating a category post content takes quite a few steps. Fill out the category post content below to present users relevant information of our website.',
        'field_container' => [
            0 => [
                'type' => 'custom',
                'label' => 'general',
                'default_display' => 'show',
                'field' => [
                    0 => [
                        'type' => 'text',
                        'id' => 'title',
                        'name' => 'title',
                        'label' => 'category title',
                        'placeholder' => 'Enter category title here',
                        'message_error' => [
                            'required' => 'Title Required',
                        ],
                        'required' => 'yes',
                        'width' => '6',
                        'same_as_default' => 'yes',
                    ],
                    1 => [
                        'type' => 'text',
                        'id' => 'category_slug',
                        'name' => 'category_slug',
                        'label' => 'category slug',
                        'placeholder' => 'Enter category slug here',
                        'message_error' => [
                            'required' => 'Slug Required',
                        ],
                        'required' => 'yes',
                        'width' => '6',
                        'same_as_default' => 'yes',
                        'disabled_on_edit' => 'yes',
                    ],
                    2 => [
                        'type' => 'editor',
                        'id' => 'content',
                        'name' => 'content',
                        'label' => 'content',
                        'placeholder' => '',
                        'message_error' => '',
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                ],
            ],
            1 => [
                'type' => 'media',
                'label' => 'media',
                'default_display' => 'show',
                'use_panel' => 'yes',
                'feature' => ['image'],
            ],
            2 => [
                'type' => 'seo',
                'label' => 'search engine optimization',
                'default_display' => 'hide',
                'feature' => ['keywords','advanced'],
            ],
        ],
    ],
    'post' => [
        'module_id' => 'post',
        'module_name' => 'post',
        'module_action' => [
            'index' => 'index',
            'create' => 'create',
            'store' => 'create',
            'edit' => 'edit',
            'update' => 'edit',
            'delete' => 'delete',
        ],
        'template' => 'post',
        'instruction' => 'Creating a post takes quite a few steps. Fill out the post content below to present users relevant information of our website.',
        'field_container' => [
            0 => [
                'type' => 'custom',
                'label' => 'general',
                'default_display' => 'show',
                'field' => [
                    0 => [
                        'type' => 'text',
                        'id' => 'title',
                        'name' => 'title',
                        'label' => 'post title',
                        'placeholder' => 'Enter post title here',
                        'message_error' => [
                            'required' => 'Title Required',
                        ],
                        'required' => 'yes',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                    2 => [
                        'type' => 'select',
                        'id' => 'category_id',
                        'name' => 'category_id',
                        'label' => 'post category ',
                        'placeholder' => 'Nothing Selected',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'datasource' => '#select_basic_2_datasource',
                        'multiselect' => 'yes',
                        'required' => 'no',
                        'width' => '6',
                        'same_as_default' => 'yes',
                    ],
                    3 => [
                        'type' => 'select',
                        'id' => 'related_id',
                        'name' => 'related_id',
                        'label' => 'Related Product',
                        'placeholder' => 'Nothing Selected',
                        'message_error' => [
                            'required' => 'Please choose at least one option',
                        ],
                        'datasource' => '#select_basic_3_datasource',
                        'multiselect' => 'yes',
                        'required' => 'no',
                        'width' => '6',
                        'same_as_default' => 'yes',
                    ],
                    4 => [
                        'type' => 'textareacounter',
                        'id' => 'short_description',
                        'name' => 'short_description',
                        'label' => 'Short Description',
                        'placeholder' => 'This short description has a limit of 170 characters',
                        'message_error' => '',
                        'required' => 'no',
                        'width' => '12',
                        'row' => '5',
                        'maxlength' => '230',
                        'same_as_default' => 'yes',
                    ],
                    5 => [
                        'type' => 'editor',
                        'id' => 'content',
                        'name' => 'content',
                        'label' => 'content',
                        'placeholder' => '',
                        'message_error' => '',
                        'required' => 'no',
                        'width' => '12',
                        'same_as_default' => 'yes',
                    ],
                ],
            ],
            1 => [
                'type' => 'media',
                'label' => 'media',
                'default_display' => 'show',
                'use_panel' => 'yes',
                'feature' => ['image','gallery'],
            ],
            2 => [
                'type' => 'seo',
                'label' => 'search engine optimization',
                'default_display' => 'hide',
                'feature' => ['keywords','advanced'],
            ],
        ],
    ],
];
